name: qrshare
version: '1.0.0'
summary: s
description: |
  D.

base: core22
confinement: strict
grade: stable

architectures:
  - build-on: [amd64]
  - build-on: [arm64]
parts:
  qrcp:
    plugin: go
    source-type: git
    source: https://github.com/claudiodangelis/qrcp.git
    source-tag: '0.11.2'
    build-snaps:
      - go

  qrshare:
    source: https://github.com/faveoled/qrshare.git
    source-commit: '8674a230758a2982e63daedc6b16e288ad93bafc'
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - curl
      - jq
      - libjsoncpp-dev
    stage-packages:
      - libjsoncpp25
      - zenity          

apps:
  qrshare:
    command: qrshare
    extensions: [gnome]
    plugs:
      - home
      - network
      - network-bind
      - process-control
    environment:
      QRCP_CMD: $SNAP/bin/qrcp
